"""add_reservation_events

Revision ID: 1f5e9c302566
Revises: 244f7804d41e
Create Date: 2026-01-06 16:27:09.235160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f5e9c302566'
down_revision: Union[str, Sequence[str], None] = '244f7804d41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_status_id'], ['reservation_status.id'], ),
    sa.ForeignKeyConstraint(['old_status_id'], ['reservation_status.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_events_id'), 'reservation_events', ['id'], unique=False)
    op.add_column('books', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    op.drop_index(op.f('ix_reservation_events_id'), table_name='reservation_events')
    op.drop_table('reservation_events')
    # ### end Alembic commands ###
