"""initial_schema

Revision ID: 57f3d3674406
Revises: 
Create Date: 2026-01-07 02:16:53.679724

"""

import uuid
from datetime import datetime, timedelta
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57f3d3674406"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enumerator", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_status_enumerator"), "book_status", ["enumerator"], unique=True
    )
    op.create_index(op.f("ix_book_status_id"), "book_status", ["id"], unique=False)
    op.create_table(
        "loan_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enumerator", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_status_enumerator"), "loan_status", ["enumerator"], unique=True
    )
    op.create_index(op.f("ix_loan_status_id"), "loan_status", ["id"], unique=False)
    op.create_table(
        "reservation_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enumerator", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enumerator"),
    )
    op.create_index(
        op.f("ix_reservation_status_id"), "reservation_status", ["id"], unique=False
    )
    op.create_table(
        "user_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enumerator", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_status_enumerator"), "user_status", ["enumerator"], unique=True
    )
    op.create_index(op.f("ix_user_status_id"), "user_status", ["id"], unique=False)
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_key", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["book_status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_book_key"), "books", ["book_key"], unique=True)
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_key", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["user_status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_user_key"), "users", ["user_key"], unique=True)
    op.create_table(
        "book_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("old_status_id", sa.Integer(), nullable=True),
        sa.Column("new_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_status_id"],
            ["book_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["old_status_id"],
            ["book_status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_events_id"), "book_events", ["id"], unique=False)
    op.create_table(
        "loans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loan_key", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "due_date", postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False
        ),
        sa.Column(
            "return_date",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=True,
        ),
        sa.Column("fine_amount", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["loan_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loans_id"), "loans", ["id"], unique=False)
    op.create_index(op.f("ix_loans_loan_key"), "loans", ["loan_key"], unique=True)
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_key", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column(
            "reserved_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["reservation_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservations_id"), "reservations", ["id"], unique=False)
    op.create_index(
        op.f("ix_reservations_reservation_key"),
        "reservations",
        ["reservation_key"],
        unique=True,
    )
    op.create_table(
        "user_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("old_status_id", sa.Integer(), nullable=True),
        sa.Column("new_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["new_status_id"],
            ["user_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["old_status_id"],
            ["user_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_events_id"), "user_events", ["id"], unique=False)
    op.create_table(
        "loan_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loan_id", sa.Integer(), nullable=False),
        sa.Column("old_status_id", sa.Integer(), nullable=True),
        sa.Column("new_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_status_id"],
            ["loan_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["old_status_id"],
            ["loan_status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loan_events_id"), "loan_events", ["id"], unique=False)
    op.create_table(
        "reservation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("old_status_id", sa.Integer(), nullable=True),
        sa.Column("new_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=3),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["new_status_id"],
            ["reservation_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["old_status_id"],
            ["reservation_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reservation_events_id"), "reservation_events", ["id"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO user_status (enumerator, translation) VALUES
        ('active', 'Ativo'),
        ('suspended', 'Suspenso'),
        ('deactivated', 'Desativado')
    """
    )

    op.execute(
        """
        INSERT INTO book_status (enumerator, translation) VALUES
        ('available', 'Disponível'),
        ('unavailable', 'Indisponível'),
        ('loaned', 'Emprestado')
    """
    )

    op.execute(
        """
        INSERT INTO loan_status (enumerator, translation) VALUES
        ('active', 'Ativo'),
        ('returned', 'Devolvido')
    """
    )

    op.execute(
        """
        INSERT INTO reservation_status (enumerator, translation) VALUES
        ('active', 'Ativa'),
        ('cancelled', 'Cancelada'),
        ('completed', 'Completada')
    """
    )

    op.execute(
        """
        INSERT INTO users (user_key, name, email, status_id) VALUES
        ('{}'::uuid, 'João Silva', 'joao.silva@email.com', 1),
        ('{}'::uuid, 'Maria Santos', 'maria.santos@email.com', 1),
        ('{}'::uuid, 'Pedro Oliveira', 'pedro.oliveira@email.com', 1),
        ('{}'::uuid, 'Ana Costa', 'ana.costa@email.com', 1),
        ('{}'::uuid, 'Carlos Ferreira', 'carlos.ferreira@email.com', 1),
        ('{}'::uuid, 'Juliana Alves', 'juliana.alves@email.com', 1),
        ('{}'::uuid, 'Roberto Lima', 'roberto.lima@email.com', 2),
        ('{}'::uuid, 'Fernanda Souza', 'fernanda.souza@email.com', 1),
        ('{}'::uuid, 'Lucas Pereira', 'lucas.pereira@email.com', 3),
        ('{}'::uuid, 'Patrícia Ribeiro', 'patricia.ribeiro@email.com', 1)
    """.format(
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
        )
    )

    op.execute(
        """
        INSERT INTO books (book_key, title, author, genre, status_id) VALUES
        ('{}'::uuid, '1984', 'George Orwell', 'Ficção Científica', 1),
        ('{}'::uuid, 'Dom Casmurro', 'Machado de Assis', 'Romance', 1),
        ('{}'::uuid, 'O Senhor dos Anéis', 'J.R.R. Tolkien', 'Fantasia', 1),
        ('{}'::uuid, 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Fantasia', 1),
        ('{}'::uuid, 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Fábula', 1),
        ('{}'::uuid, 'Cem Anos de Solidão', 'Gabriel García Márquez', 'Realismo Mágico', 1),
        ('{}'::uuid, 'O Código Da Vinci', 'Dan Brown', 'Thriller', 1),
        ('{}'::uuid, 'A Culpa é das Estrelas', 'John Green', 'Romance', 1),
        ('{}'::uuid, 'Clean Code', 'Robert C. Martin', 'Tecnologia', 1),
        ('{}'::uuid, 'Sapiens', 'Yuval Noah Harari', 'História', 1),
        ('{}'::uuid, 'O Hobbit', 'J.R.R. Tolkien', 'Fantasia', 1),
        ('{}'::uuid, 'A Revolução dos Bichos', 'George Orwell', 'Fábula', 1),
        ('{}'::uuid, 'Orgulho e Preconceito', 'Jane Austen', 'Romance', 1),
        ('{}'::uuid, 'Crime e Castigo', 'Fiódor Dostoiévski', 'Romance Psicológico', 1),
        ('{}'::uuid, 'O Nome da Rosa', 'Umberto Eco', 'Mistério', 1),
        ('{}'::uuid, 'A Metamorfose', 'Franz Kafka', 'Ficção Moderna', 1),
        ('{}'::uuid, 'O Alienista', 'Machado de Assis', 'Conto', 1),
        ('{}'::uuid, 'Admirável Mundo Novo', 'Aldous Huxley', 'Ficção Científica', 1),
        ('{}'::uuid, 'Fahrenheit 451', 'Ray Bradbury', 'Ficção Científica', 1),
        ('{}'::uuid, 'O Cortiço', 'Aluísio Azevedo', 'Naturalismo', 1),
        ('{}'::uuid, 'Grande Sertão: Veredas', 'Guimarães Rosa', 'Romance', 1),
        ('{}'::uuid, 'Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'Romance', 1),
        ('{}'::uuid, 'A Moreninha', 'Joaquim Manuel de Macedo', 'Romance', 1),
        ('{}'::uuid, 'Iracema', 'José de Alencar', 'Romance Indianista', 1),
        ('{}'::uuid, 'O Coruja', 'Aluísio Azevedo', 'Romance', 1)
    """.format(
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
            uuid.uuid4(),
        )
    )

    op.execute(
        """
        INSERT INTO loans (loan_key, user_id, book_id, status_id, start_date, due_date, return_date, fine_amount) VALUES
        ('{}'::uuid, 1, 1, 1, NOW() - INTERVAL '5 days', NOW() + INTERVAL '9 days', NULL, 0.0),
        ('{}'::uuid, 2, 2, 1, NOW() - INTERVAL '3 days', NOW() + INTERVAL '11 days', NULL, 0.0),
        ('{}'::uuid, 1, 4, 2, NOW() - INTERVAL '30 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '18 days', 0.0),
        ('{}'::uuid, 2, 5, 2, NOW() - INTERVAL '25 days', NOW() - INTERVAL '11 days', NOW() - INTERVAL '13 days', 0.0)
    """.format(
            uuid.uuid4(), uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
        )
    )

    op.execute(
        """
        INSERT INTO reservations (reservation_key, user_id, book_id, status_id, reserved_at, expires_at, completed_at) VALUES
        ('{}'::uuid, 3, 3, 1, NOW() - INTERVAL '2 days', NOW() + INTERVAL '5 days', NULL),
        ('{}'::uuid, 4, 6, 3, NOW() - INTERVAL '10 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '8 days')
    """.format(
            uuid.uuid4(), uuid.uuid4()
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM reservation_events")
    op.execute("DELETE FROM reservations")
    op.execute("DELETE FROM loan_events")
    op.execute("DELETE FROM loans")
    op.execute("DELETE FROM book_events")
    op.execute("DELETE FROM user_events")
    op.execute("DELETE FROM books")
    op.execute("DELETE FROM users")
    op.execute("DELETE FROM user_status")
    op.execute("DELETE FROM book_status")
    op.execute("DELETE FROM loan_status")
    op.execute("DELETE FROM reservation_status")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservation_events_id"), table_name="reservation_events")
    op.drop_table("reservation_events")
    op.drop_index(op.f("ix_loan_events_id"), table_name="loan_events")
    op.drop_table("loan_events")
    op.drop_index(op.f("ix_user_events_id"), table_name="user_events")
    op.drop_table("user_events")
    op.drop_index(op.f("ix_reservations_reservation_key"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_loans_loan_key"), table_name="loans")
    op.drop_index(op.f("ix_loans_id"), table_name="loans")
    op.drop_table("loans")
    op.drop_index(op.f("ix_book_events_id"), table_name="book_events")
    op.drop_table("book_events")
    op.drop_index(op.f("ix_users_user_key"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_index(op.f("ix_books_book_key"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_user_status_id"), table_name="user_status")
    op.drop_index(op.f("ix_user_status_enumerator"), table_name="user_status")
    op.drop_table("user_status")
    op.drop_index(op.f("ix_reservation_status_id"), table_name="reservation_status")
    op.drop_table("reservation_status")
    op.drop_index(op.f("ix_loan_status_id"), table_name="loan_status")
    op.drop_index(op.f("ix_loan_status_enumerator"), table_name="loan_status")
    op.drop_table("loan_status")
    op.drop_index(op.f("ix_book_status_id"), table_name="book_status")
    op.drop_index(op.f("ix_book_status_enumerator"), table_name="book_status")
    op.drop_table("book_status")
    # ### end Alembic commands ###
