"""initial_schema

Revision ID: 57f3d3674406
Revises: 
Create Date: 2026-01-07 02:16:53.679724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f3d3674406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enumerator', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_status_enumerator'), 'book_status', ['enumerator'], unique=True)
    op.create_index(op.f('ix_book_status_id'), 'book_status', ['id'], unique=False)
    op.create_table('loan_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enumerator', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_status_enumerator'), 'loan_status', ['enumerator'], unique=True)
    op.create_index(op.f('ix_loan_status_id'), 'loan_status', ['id'], unique=False)
    op.create_table('reservation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enumerator', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enumerator')
    )
    op.create_index(op.f('ix_reservation_status_id'), 'reservation_status', ['id'], unique=False)
    op.create_table('user_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enumerator', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_status_enumerator'), 'user_status', ['enumerator'], unique=True)
    op.create_index(op.f('ix_user_status_id'), 'user_status', ['id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_key', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['book_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_book_key'), 'books', ['book_key'], unique=True)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['user_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_key'), 'users', ['user_key'], unique=True)
    op.create_table('book_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['new_status_id'], ['book_status.id'], ),
    sa.ForeignKeyConstraint(['old_status_id'], ['book_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_events_id'), 'book_events', ['id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_key', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('return_date', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.Column('fine_amount', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['loan_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_key'), 'loans', ['loan_key'], unique=True)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_key', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('reserved_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['reservation_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_index(op.f('ix_reservations_reservation_key'), 'reservations', ['reservation_key'], unique=True)
    op.create_table('user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_status_id'], ['user_status.id'], ),
    sa.ForeignKeyConstraint(['old_status_id'], ['user_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.create_table('loan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['new_status_id'], ['loan_status.id'], ),
    sa.ForeignKeyConstraint(['old_status_id'], ['loan_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_events_id'), 'loan_events', ['id'], unique=False)
    op.create_table('reservation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_status_id'], ['reservation_status.id'], ),
    sa.ForeignKeyConstraint(['old_status_id'], ['reservation_status.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_events_id'), 'reservation_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_events_id'), table_name='reservation_events')
    op.drop_table('reservation_events')
    op.drop_index(op.f('ix_loan_events_id'), table_name='loan_events')
    op.drop_table('loan_events')
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_reservations_reservation_key'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_loans_loan_key'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_book_events_id'), table_name='book_events')
    op.drop_table('book_events')
    op.drop_index(op.f('ix_users_user_key'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_book_key'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_user_status_id'), table_name='user_status')
    op.drop_index(op.f('ix_user_status_enumerator'), table_name='user_status')
    op.drop_table('user_status')
    op.drop_index(op.f('ix_reservation_status_id'), table_name='reservation_status')
    op.drop_table('reservation_status')
    op.drop_index(op.f('ix_loan_status_id'), table_name='loan_status')
    op.drop_index(op.f('ix_loan_status_enumerator'), table_name='loan_status')
    op.drop_table('loan_status')
    op.drop_index(op.f('ix_book_status_id'), table_name='book_status')
    op.drop_index(op.f('ix_book_status_enumerator'), table_name='book_status')
    op.drop_table('book_status')
    # ### end Alembic commands ###
