"""initial_sync

Revision ID: 69fb53408791
Revises: 
Create Date: 2026-01-03 23:52:08.041374

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '69fb53408791'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_events_id'), 'book_events', ['id'], unique=False)
    op.drop_constraint(op.f('book_status_enumerator_key'), 'book_status', type_='unique')
    op.create_index(op.f('ix_book_status_enumerator'), 'book_status', ['enumerator'], unique=True)
    op.create_index(op.f('ix_book_status_id'), 'book_status', ['id'], unique=False)
    op.drop_constraint(op.f('books_book_key_key'), 'books', type_='unique')
    op.create_index(op.f('ix_books_book_key'), 'books', ['book_key'], unique=True)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_loan_events_id'), 'loan_events', ['id'], unique=False)
    op.drop_constraint(op.f('loan_status_enumerator_key'), 'loan_status', type_='unique')
    op.create_index(op.f('ix_loan_status_enumerator'), 'loan_status', ['enumerator'], unique=True)
    op.create_index(op.f('ix_loan_status_id'), 'loan_status', ['id'], unique=False)
    op.drop_constraint(op.f('loans_loan_key_key'), 'loans', type_='unique')
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_key'), 'loans', ['loan_key'], unique=True)
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.drop_constraint(op.f('user_status_enumerator_key'), 'user_status', type_='unique')
    op.create_index(op.f('ix_user_status_enumerator'), 'user_status', ['enumerator'], unique=True)
    op.create_index(op.f('ix_user_status_id'), 'user_status', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_user_key_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_key'), 'users', ['user_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_key'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_user_key_key'), 'users', ['user_key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_status_id'), table_name='user_status')
    op.drop_index(op.f('ix_user_status_enumerator'), table_name='user_status')
    op.create_unique_constraint(op.f('user_status_enumerator_key'), 'user_status', ['enumerator'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_index(op.f('ix_loans_loan_key'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.create_unique_constraint(op.f('loans_loan_key_key'), 'loans', ['loan_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_loan_status_id'), table_name='loan_status')
    op.drop_index(op.f('ix_loan_status_enumerator'), table_name='loan_status')
    op.create_unique_constraint(op.f('loan_status_enumerator_key'), 'loan_status', ['enumerator'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_loan_events_id'), table_name='loan_events')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_book_key'), table_name='books')
    op.create_unique_constraint(op.f('books_book_key_key'), 'books', ['book_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_book_status_id'), table_name='book_status')
    op.drop_index(op.f('ix_book_status_enumerator'), table_name='book_status')
    op.create_unique_constraint(op.f('book_status_enumerator_key'), 'book_status', ['enumerator'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_book_events_id'), table_name='book_events')
    # ### end Alembic commands ###
